spring:
  datasource:
    url: jdbc:mysql://172.31.205.29:3306/taroco-authentication?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: taroco-authentication
    password: Taroco!@#$12
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 100
      maximum-pool-size: 100
      pool-name: Taroco-Authentication-HikariCP
  redis:
    host: 172.31.205.29
    port: 6379
    password: REDIS1.t!@#
    database: 1
  session:
    store-type: redis

server:
  tomcat:
    min-spare-threads: 100
    accept-count: 10000

taroco:
  oauth2:
    key-store:
      location: classpath:taroco.jks
      secret: taroco!@#$
      alias: taroco
    url-permit-all:
      - /smsCode/*
      - /actuator/**
      - /login/mobile
      - /oauth/mobile
      - /oauth/exit
      - /webjars/**
      - /static/**
      - /**/*.css
      - /**/*.jpg
      - /**/*.jpeg
      - /**/*.png
      - /**/*.svg
      - /**/*.woff2
      - /**/*.js
      - /**/*.ico
