server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: debug

spring:
  application:
    name: taroco-authentication-server
  datasource:
    url: jdbc:mysql://118.190.154.85:3306/taroco-authentication?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: taroco-authentication
    password: taroco-authentication
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: Taroco-Authentication-HikariCP
  redis:
    host: 127.0.0.1
    port: 6379
    password: hyman
    database: 0


taroco:
  oauth2:
    key-store:
      location: classpath:taroco.jks
      secret: taroco!@#$
      alias: taroco
    url-permit-all:
      - /actuator/**
      - /oauth/mobile
      - /webjars/**
      - /static/**
      - /**/*.css
      - /**/*.jpg
      - /**/*.jpeg
      - /**/*.png
      - /**/*.svg
      - /**/*.woff2
      - /**/*.js
      - /**/*.ico
